=== KongTu/H1_ForwardMultAnalyzer/TUnfold/unfolding/binning.dtd
<!-- TUnfold Version V17.7 -->
<!ELEMENT TUnfoldBinning (BinningNode+,Histograms*,UnfoldingInput,UnfoldingOutput) >
<!ELEMENT BinningNode (BinningNode*|(Binfactorlist?,Axis)|Bins) >
<!ATTLIST BinningNode name CDATA #REQUIRED firstbin CDATA "-1"
    factor CDATA "1.">
<!ELEMENT Axis ((Bin+,Axis?)|(Axis)) >
<!ATTLIST Axis name CDATA #REQUIRED lowEdge CDATA #REQUIRED>
<!ELEMENT Binfactorlist (#PCDATA)>
<!ATTLIST Binfactorlist length CDATA #REQUIRED>
<!ELEMENT Bin EMPTY>
<!ATTLIST Bin width CDATA #REQUIRED location CDATA #IMPLIED
    center CDATA #IMPLIED repeat CDATA #IMPLIED>
<!ELEMENT Bins (BinLabel)* >
<!ATTLIST Bins nbin CDATA #REQUIRED>
<!ELEMENT BinLabel EMPTY>
<!ATTLIST BinLabel index CDATA #REQUIRED name CDATA #REQUIRED>
<!ELEMENT Histograms (Histogram+)>
<!ELEMENT Histogram (mergeBins)* >
<!ATTLIST Histogram name CDATA #REQUIRED distribution CDATA #REQUIRED option CDATA "">
<!ELEMENT mergeBins EMPTY >
<!ATTLIST mergeBins firstCenter CDATA #REQUIRED lastCenter CDATA #REQUIRED>
<!ELEMENT UnfoldingInput (#PCDATA) >
<!ATTLIST UnfoldingInput dataluminosity CDATA #REQUIRED>
<!ELEMENT UnfoldingOutput (#PCDATA) >
<!ATTLIST UnfoldingOutput>

=== KongTu/H1_ForwardMultAnalyzer/TUnfold/unfolding_backup/binning_etay.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE TUnfoldBinning SYSTEM "binning.dtd">
<TUnfoldBinning>
  <BinningNode name="genQ2">
    <BinningNode name="Q2MC_es_mini:5" /> <!-- underflow bin -->
    <BinningNode name="Q2MC_es_mini:10" />
    <BinningNode name="Q2MC_es_mini:20" />
    <BinningNode name="Q2MC_es_mini:40" />
    <BinningNode name="Q2MC_es_mini:100" /> 
  </BinningNode>
  <BinningNode name="genY">
    <BinningNode name="yMC_es_mini:0.0375" />
    <BinningNode name="yMC_es_mini:0.075" />
    <BinningNode name="yMC_es_mini:0.15" />
    <BinningNode name="yMC_es_mini:0.3" />
    <BinningNode name="yMC_es_mini:0.6" />
  </BinningNode>
  <BinningNode name="genNtrack">
    <Axis name="ntrackMC" lowEdge="-0.5">
      <Bin repeat="4" width="1"/> <!-- -0.5 .. 3.5 -->
      <Bin repeat="2" width="2"/> <!-- 3.5 .. 7.5 -->
      <Bin repeat="1" width="4"/> <!-- 7.5 .. 11.5 -->
      <Bin repeat="1" width="6"/> <!-- 11.5 .. 17.5 -->
      <Bin location="overflow" width="6"/> <!-- overflow -->
    </Axis>
  </BinningNode>
  <BinningNode name="recQ2">
    <BinningNode name="4:Q2REC_es_mini:5" /> <!-- underflow bin -->
    <BinningNode name="Q2REC_es_mini:7" />
    <BinningNode name="Q2REC_es_mini:10" />
    <BinningNode name="Q2REC_es_mini:14" />
    <BinningNode name="Q2REC_es_mini:20" />
    <BinningNode name="Q2REC_es_mini:28" />
    <BinningNode name="Q2REC_es_mini:40" />
    <BinningNode name="Q2REC_es_mini:56" />
    <BinningNode name="Q2REC_es_mini:100" />
  </BinningNode>
  <BinningNode name="recY">
    <BinningNode name="yREC_es_mini:0.0375" />  <!-- underflow bin -->
    <BinningNode name="yREC_es_mini:0.0525" />
    <BinningNode name="yREC_es_mini:0.075" />
    <BinningNode name="yREC_es_mini:0.105" />
    <BinningNode name="yREC_es_mini:0.15" />
    <BinningNode name="yREC_es_mini:0.21" />
    <BinningNode name="yREC_es_mini:0.3" />
    <BinningNode name="yREC_es_mini:0.42" />
    <BinningNode name="yREC_es_mini:0.6" />
  </BinningNode>
  <BinningNode name="recNtrack">
    <Axis name="ntrackREC" lowEdge="-0.5">
      <Bin repeat="8" width="1"/> <!-- -0.5 .. 7.5 -->
      <Bin repeat="2" width="2"/> <!-- 7.5 .. 11.5 -->
      <Bin repeat="2" width="3"/> <!-- 11.5 .. 14.5 -->
      <Bin location="overflow" width="32"/>
    </Axis>
  </BinningNode>
  <BinningNode name="etaBins">
    <BinningNode name="-1.2:eta:0.2" />
    <BinningNode name="-0.5:eta:0.9" />
    <BinningNode name="0.2:eta:1.6" />
  </BinningNode>
  <UnfoldingInput dataluminosity="136">
    unfoldingInput_yetalab.root
  </UnfoldingInput>
  <UnfoldingOutput>
    unfoldingOutput_yetalab.root
  </UnfoldingOutput>
</TUnfoldBinning>
